fsHandlerBaseDir: /var/lib/tftpboot
tftp:
  ip: "0.0.0.0"
  port: 69
  retransmissions: 3
  maxParallelConnections: 10
  # Disabled by default ("0s")
  filetransfertimeout: "60s"
  metrics:
    enabled: true
    route: "/metrics"
    port: 9100
