name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Task
      run: go install github.com/go-task/task/v3/cmd/task@latest
    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@latest
    - name: Generate mocks
      run: go generate ./pkg/... ./internal/...
    - name: Test
      run: task unit-tests
